language: generic
sudo: require
services:
    - docker

before_install:
    - docker build -t nimaadocker/react-complex-app-test -f ./client/Dockerfile.dev ./client
    
scripts:
    - docker run -e CI=true nimaadocker/react-complex-app-test npm test

after_success:
    - docker build -t nimaadocker/react-complex-app-client ./client 
    - docker build -t nimaadocker/react-complex-app-nginx ./nginx
    - docker build -t nimaadocker/react-complex-app-server ./server
    - docker build -t nimaadocker/react-complex-app-worker ./worker
# login to the docker CLI thorogh Linux command --> we need to login to docker hub account from Terminal
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hubb
    - docker push nimaadocker/react-complex-app-client
    - docker push nimaadocker/react-complex-app-nginx
    - docker push nimaadocker/react-complex-app-server
    - docker push nimaadocker/react-complex-app-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker_complex_app"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-711940374483"
    bucket_path: "docker_complex_app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


